version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: "weekly"
    labels:
      - "kind/deps"
    versioning-strategy: 'increase'

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "kind/deps"
